# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://br13.netlify.app"

# Comment out the url above and uncomment the one below if running locally
# url: "http://localhost:4000"

# The ability to use custom themes.
style:
  theme: "original"

# Event information.
event:
  name: "Battle Royale XIII"
  description: "24 Hour LAN Party!"
  # Frequently asked questions.
  faq_left:
    - question: "> Who can participate in the Battle Royale?"
      answer: >
        We’re glad you asked! Absolutely anyone over 12 years of age can
        participate in Battle Royale. Many students from, Carleton University,
        University of Ottawa, and Algonquin College attend, so it’s a great
        opportunity to socialize with them.

    - question: "> Do I have to stay at the Battle Royale for 24 hours straight?"
      answer: >
        Of course not! Once all of your games are done, you are free to go, but since Battle Royale is all about fun and socializing, we strongly recommend you stay and meet new people! However, DO NOT skip any of your games! If you do, you will be automatically forfeited and disqualified from your tournament (and you DON’T want that).

    - question: "> Can I return my ticket or give it to someone else?"
      answer: >
        All sales are final, meaning we do not offer refunds for tickets. However, tickets are transferable, meaning that you can give your ticket to someone else. However, if a tournament doesn’t receive enough competitors, it will be cancelled, with no ticket refund. You can prevent this by inviting your friends to play in that tournament!

  faq_right:
    - question: "> What happens when I join?"
      answer: >
        Once you enter Battle Royale, you’ll be almost instantly immersed in the vibrant atmosphere. We ask that you make your way to the registration channel, where you’ll be able to sign in. Our volunteers will always be around, so feel free to ask them if you have any questions or if you need help.

    - question: "> What's the difference between a major and minor tournament?"
      answer: >
        Major tournaments are the games at Battle Royale that are the most popular. This year, League of Legends and CS:GO will be the major tournaments. Major tournaments are expected to have more competitors, so the competition will be higher (and also more epic). Because of this, prizes for major tournaments will be substantially better and worth more money compared to the minor tournaments.

    - question: "> What happens if I miss my game or it overlaps with another?"
      answer: >
        We do our best to avoid scheduling conflicts. However should one arise, the major tournament will always take priority. This means you may need to forfeit from your minor tournament, though we’ll do our best to prevent this!

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
